### ISSUE TITLE
Monterey for ARMv8 Raspberry Pi 4B 8GB ?

### ISSUE THREAD

**Issue by juanpc2018** [pearOS-archlinux/iso#13]
just a thought.

there is a video on YT how to install macOS 7.5.5 Color in a Pi 4B.
looks interesting.

64-Bit Pi OS
https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-04-07/2022-04-04-raspios-bullseye-arm64.img.xz.torrent
https://www.raspberrypi.com/software/operating-systems/
https://www.tomshardware.com/news/raspberry-pi-4-8gb-tested
https://forums.raspberrypi.com/viewtopic.php?f=117&t=275370
https://www.raspberrypi.com/software/

There are also some Nice Qualcomm, MediaTek & Cortex Laptops.
https://store.acer.com/en-us/laptops?processor_type%5B0%5D=Qualcomm%C2%AE+Snapdragon%E2%84%A2&processor_type%5B1%5D=Cortex%C2%AE

4GB
Acer Chromebook 311 - CB311-11H-K3US 
Acer Chromebook 314 CB314-2H-K3YM
Acer Chromebook Spin 513 - CP513-1H-S682
Acer Chromebook Spin 513 - CP513-1H-S60F 
Samsung Galaxy Book Go 5G
Lenovo Miix 630

4GB/8GB
Acer Spin 7
Asus NovaGo
HP Envy x2
Lenovo Flex 5G

https://www.digitaltrends.com/computing/hp-envy-x2-qualcomm-snapdragon-835-processor-review/
https://www.digitaltrends.com/computing/asus-novago-first-gigabit-lte-capable-laptop/

There is 1 Linux distro that works on Apple M1, but does Not have GPU HW Acceleration and other features.
its RAW.

There is also a lot of ARM Tablets, but Pi is more universal.

**Comment by juanpc2018** [comment]
https://github.com/juanpc2018/x86_64-is-dead

**Comment by alxb421** [comment]
For developing on other platform, I need to own something that runs on that platform, so I can do tests and debugging
