### ISSUE TITLE
3D SBS Desktop idea

### ISSUE THREAD

**Issue by juanpc2018** [pearOS-archlinux/iso#14]
Sadly 3D TVs are Not popular...

and passive 3D goggles, lower resolution half.
Active 3D glasses are heavy for long periods of time, and need constant recharge.

there are 3D TVs without goggles, but are FAT & Rare.

Side-by-Side 3D works like X.
when the 2 images are equal, has a middle point.
when 2 images shift <-> outwards, has a far away perception,
when 2 images shift >< inwards, has a closer perception.
.>-<
.-X-.
.<->

Passive 4K 3D SBS would be awesome for a Desktop environment.

There is also the HP G2 better than Oculus, similar to DJI Goggles exept FPV that are Analog input for low latency.

The Dock Zoom On Hover really could look Closer in 3D.
Active windows, pop-up windows, could have true depth.
old OSX had a Panel Bar with Shadow, there is a optional in Apple store for New OSX.

**Comment by alxb421** [comment]
Thank you for the suggestion. I will try to adapt
