### ISSUE TITLE
Dock Bounce feels it can improve.

### ISSUE THREAD

**Issue by juanpc2018** [pearOS-archlinux/iso#17]
Bounce feels like Sun Gravity, Not Earth Gravity.
Mars or Moon would be better.

https://www.youtube.com/watch?v=xypBGd86ogw
https://youtu.be/ZLW1PspVf6Y
https://www.youtube.com/watch?v=IfXNjuoqt0Q

Baskettball example:
https://www.youtube.com/watch?v=ZvgJ7mVxeg0
https://youtu.be/AVM1Y4RUd1g
https://www.youtube.com/watch?v=m1p6AuY6wLU
https://youtu.be/21RPLP1MV9w

second example is wrong, floor is absorbing energy, ball is too heavy or not inflated properly.

**Comment by alxb421** [comment]
cannot change the bounce, because that animation is part of Latte Dock ( https://github.com/KDE/Latte-dock )
