### ISSUE TITLE
pearOS Monterey Memory performance is behind Kubuntu 21.10

### ISSUE THREAD

**Issue by juanpc2018** [pearOS-archlinux/iso#20]
creating a Ram drive with rapiddisk 8.2.0,
XFS or Ext4,.

testing with gnome-disks Benchmark.

Kubuntu 21.10 Kernel 5.13.0.51-generic
vs.
pearOS Kernel 5.14.-oem

Benchmark result:
Kubuntu 11GB/s Read Only,
Flat Line.
5GB/s R&W, near flat line, some dips.

pearOS Monterey its very unstable Dips -50% every x MB.

Test parameter: 100MB files. ("one cero more")

**Comment by alxb421** [comment]
will change up some things in the near future
