### ISSUE TITLE
Error. Error. Error

### ISSUE THREAD

**Issue by CatMow** [pearOS-archlinux/iso#23]
![image](https://user-images.githubusercontent.com/84914492/185009786-f7059147-e6f4-4cd7-a227-65952f86af4e.png)
vmware latest version

**Comment by alxb421** [comment]
wrong vmware settings. Try another VM settings, another VM software or live test it without install

**Comment by CatMow** [comment]
alright ty!

**Comment by CatMow** [comment]
ill try that
