### ISSUE TITLE
Password for Default User

### ISSUE THREAD

**Issue by izaxYT14538** [pearOS-archlinux/iso#24]
Hi Guys i installed pearOS NiceC0re On a testing machine when install finished i rebooted and a login screen with a user named ''DEFAULT'' i tried some pass like 1234567890 or default or put nothing it doesn't work someone can help me? and i cant join the pearos server discord

**Comment by CasperOng** [comment]
All pearOS default public account shares the password: **pear** Try it!

**Comment by izaxYT14538** [comment]
> All pearOS default public account shares the password: **pear** Try it!

Thanks but is too late now im using my own ubuntu respin but thanks.
