### ISSUE TITLE
What software do you use to make pearOS

### ISSUE THREAD

**Issue by iiab76** [pearOS-archlinux/iso#26]
Not an actual issue, just wondering what you use to make pearOS releases.

**Comment by izaxYT14538** [comment]
probably they use an chroot like cubic but for arch.

**Comment by alxb421** [comment]
> Not an actual issue, just wondering what you use to make pearOS releases.

I used the Official Arch tool, called archiso, and made my own script based on that, since it cannot work alone.



> probably they use an chroot like cubic but for arch.

@izaxYT14538 that is not true. Such thing for arch would be very cool, but unf. I had to do everything by hand
