### ISSUE TITLE
NiceC0re install won't even boot

### ISSUE THREAD

**Issue by DragaBatchPro** [pearOS-archlinux/iso#31]
I use my Nicec0re install usb (created with Rufus), and i use it to install pearOS on one of my experiment laptops.
When i select the disk and click install, the progress bar just progresses up to a quarter and hangs. after that, it said that the installation was complete. I was excited, since i really wanted to try this OS, but when i try to boot, it wont even boot to the disk. I suggest you fix this. The old installers in Monterey and thiccsur were miles better than this one...

Laptop specs:
Intel core i7-5500u broadwell
8gb ram 
Intel HD 5500 graphics
GeForce GT 840M (Dosen't even work so ignore this)
Laptop released ~2015
HP brand

**Comment by alxb421** [comment]
Hello! Can you attach the install.log?
> The old installers in Monterey and thiccsur were miles better than this one 
       this is because NiceC0re targets the use of a new installer made from scratch, in which the end user may experience bugs

**Comment by danuaf** [comment]
my laptop, PC and also a virtual machine, all of them won't boot and have the same install.log file

maybe package servers are down?

install.log

==> Creating install root at /mnt

==> Installing packages to /mnt

:: Synchronizing package databases...

main downloading...

core downloading...

extra downloading...

community downloading...

alg_repo downloading...

error: target not found: electron11

==> ERROR: Failed to install packages to new root

chroot: failed to run command ‘hwclock’: No such file or directory

sed: can't read /mnt/etc/locale.gen: No such file or directory

/usr/local/bin/setup: line 233: /mnt/etc/default/grub: No such file or directory

chroot: failed to run command ‘chpasswd’: No such file or directory

cp: cannot create directory '/mnt/usr/share/': No such file or directory

cp: cannot create regular file '/mnt/usr/local/bin/bin_post': No such file or directory

chmod: cannot access '/mnt/usr/local/bin/bin_post': No such file or directory

/usr/local/bin/setup: line 246: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 247: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 248: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 249: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 250: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 251: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 252: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 253: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 254: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 255: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 256: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 257: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 258: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

/usr/local/bin/setup: line 259: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory

chroot: failed to run command ‘useradd’: No such file or directory

chroot: failed to run command ‘chpasswd’: No such file or directory

chroot: failed to run command ‘usermod’: No such file or directory

chroot: failed to run command ‘usermod’: No such file or directory

sed: can't read /mnt/etc/sudoers: No such file or directory

chroot: failed to run command ‘git’: No such file or directory

chroot: failed to run command ‘yay’: No such file or directory

/usr/local/bin/setup: line 282: plymouth-set-default-theme: command not found

chmod: cannot access '/mnt/usr/share/extras': No such file or directory

**Comment by Among555** [comment]
How do i fix this error: 
[install.log](https://github.com/pearOS-archlinux/iso/files/11906192/install.log)

**Comment by CattopyTheWeb** [comment]
@alxb421

**Comment by CattopyTheWeb** [comment]
I have the same problem

**Comment by alphaelf** [comment]
hi, i have same problem here
[install.log](https://drive.google.com/file/d/1eAy9lg0at80hkMQdLpHi4EJ9Oq71kZxp/view?usp=sharing)

**Comment by dmitrijkv** [comment]
How to solve a problem?
Who decided?

**Comment by alxb421** [comment]
I pushed an update that fixed the errors
