### ISSUE TITLE
Error install due to gnome package kit not available

### ISSUE THREAD

**Issue by AMIRTHESWARAN** [pearOS-archlinux/iso#32]
this is my log 
mount: /mnt: /dev/nvme0n1p2 already mounted on /mnt.
       dmesg(1) may have more information after failed mount system call.
mkdir: cannot create directory ‘/mnt/boot’: File exists
mount: /mnt/boot: /dev/nvme0n1p1 already mounted on /mnt/boot.
       dmesg(1) may have more information after failed mount system call.
==> Creating install root at /mnt
==> Installing packages to /mnt
:: Synchronizing package databases...
 main downloading...
 core downloading...
 extra downloading...
 community downloading...
 alg_repo downloading...
:: There are 48 members in group xorg:
:: Repository extra
   1) xf86-video-vesa  2) xorg-bdftopcf  3) xorg-docs  4) xorg-font-util  5) xorg-fonts-100dpi  6) xorg-fonts-75dpi  7) xorg-fonts-encodings  8) xorg-iceauth  9) xorg-mkfontscale  10) xorg-server  11) xorg-server-common  12) xorg-server-devel  13) xorg-server-xephyr  14) xorg-server-xnest  15) xorg-server-xvfb  16) xorg-sessreg  17) xorg-setxkbmap  18) xorg-smproxy  19) xorg-x11perf  20) xorg-xauth  21) xorg-xbacklight  22) xorg-xcmsdb  23) xorg-xcursorgen  24) xorg-xdpyinfo  25) xorg-xdriinfo  26) xorg-xev  27) xorg-xgamma  28) xorg-xhost  29) xorg-xinput  30) xorg-xkbcomp  31) xorg-xkbevd  32) xorg-xkbutils  33) xorg-xkill  34) xorg-xlsatoms  35) xorg-xlsclients  36) xorg-xmodmap  37) xorg-xpr  38) xorg-xprop  39) xorg-xrandr  40) xorg-xrdb  41) xorg-xrefresh  42) xorg-xset  43) xorg-xsetroot  44) xorg-xvinfo  45) xorg-xwayland  46) xorg-xwd  47) xorg-xwininfo  48) xorg-xwud

Enter a selection (default=all): 
:: There are 51 members in group plasma:
:: Repository extra
   1) bluedevil  2) breeze  3) breeze-gtk  4) breeze-plymouth  5) discover  6) drkonqi  7) flatpak-kcm  8) kactivitymanagerd  9) kde-cli-tools  10) kde-gtk-config  11) kdecoration  12) kdeplasma-addons  13) kgamma5  14) khotkeys  15) kinfocenter  16) kmenuedit  17) kpipewire  18) kscreen  19) kscreenlocker  20) ksshaskpass  21) ksystemstats  22) kwallet-pam  23) kwayland-integration  24) kwin  25) kwrited  26) layer-shell-qt  27) libkscreen  28) libksysguard  29) milou  30) oxygen  31) oxygen-sounds  32) plasma-browser-integration  33) plasma-desktop  34) plasma-disks  35) plasma-firewall  36) plasma-integration  37) plasma-nm  38) plasma-pa  39) plasma-sdk  40) plasma-systemmonitor  41) plasma-thunderbolt  42) plasma-vault  43) plasma-welcome  44) plasma-workspace  45) plasma-workspace-wallpapers  46) plymouth-kcm  47) polkit-kde-agent  48) powerdevil  49) sddm-kcm  50) systemsettings  51) xdg-desktop-portal-kde

Enter a selection (default=all): error: target not found: gnome-software-packagekit-plugin

==> ERROR: Failed to install packages to new root
chroot: failed to run command ‘hwclock’: No such file or directory
sed: can't read /mnt/etc/locale.gen: No such file or directory
/usr/local/bin/setup: line 233: /mnt/etc/default/grub: No such file or directory
chroot: failed to run command ‘chpasswd’: No such file or directory
cp: cannot create directory '/mnt/usr/share/': No such file or directory
cp: cannot create regular file '/mnt/usr/local/bin/bin_post': No such file or directory
chmod: cannot access '/mnt/usr/local/bin/bin_post': No such file or directory
/usr/local/bin/setup: line 246: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 247: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 248: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 249: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 250: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 251: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 252: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 253: /mnt/etc/skel/.cmany onfig/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 254: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 255: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 256: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 257: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 258: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
/usr/local/bin/setup: line 259: /mnt/etc/skel/.config/autostart/xyz.pearos-post-install.desktop: No such file or directory
chroot: failed to run command ‘useradd’: No such file or directory
chroot: failed to run command ‘chpasswd’: No such file or directory
chroot: failed to run command ‘usermod’: No such file or directory
chroot: failed to run command ‘usermod’: No such file or directory
chroot: failed to run command ‘git’: No such file or directory
chroot: failed to run command ‘yay’: No such file or directory
/usr/local/bin/setup: line 282: plymouth-set-default-theme: command not found
chmod: cannot access '/mnt/usr/share/extras': No such file or directory

sorry for this i am using pear os from usb. cant install pear and many face this problem

**Comment by sugan0tech-fk** [comment]
facing the same issue, needs immediate assistance. Root cause gnome package kit plugin not available

**Comment by sugan0tech** [comment]
facing the same issue, needs immediate assistance. Root cause gnome package kit plugin not available

**Comment by NaveenSiva72** [comment]
facing the same issue.i found the best arch base distro but cant install 
plz say any fix

**Comment by Daniel-V-Richardson** [comment]
Try to remove that package from the installer script. I don't know whether it will work as intended after removing but you can try it.

**Comment by alxb421** [comment]
> Try to remove that package from the installer script. I don't know whether it will work as intended after removing but you can try it.

That is true! I removed the package with problem and now it is working
